### ISSUE TITLE
neomake-remarklint maker

### ISSUE THREAD

**Issue by davidosomething** [davidosomething/projects#1]
@wooorm's [remark-lint](https://github.com/wooorm/remark-lint)'s output is really annoying to parse using vim's `errorformat`

@sindresorhus has a [vfile reporter](https://github.com/sindresorhus/vfile-reporter-pretty) that formats the output in a single-line format (eslint-style) but it is not a proper [remark plugin](https://github.com/wooorm/remark/blob/master/doc/plugins.md) so would require a wrapper to use it in Vim or as a remark plugin for [remark-cli](https://github.com/wooorm/remark/tree/master/packages/remark-cli)
## TODO:

either
- go the long (and not easily maintainable) route and figure out the best multiline-errorformat for the default remark-lint settings

or
- add formatting capability to remark-lint via a proper remark plugin or as an option for the current remark-lint module

THEN
- submit the maker config to neomake upstream

Helpful:
https://github.com/nelstrom/vim-errorformat-testdrive for testing errorformats

**Comment by wooorm** [comment]
How are you using remark?

**Comment by davidosomething** [comment]
For testing I was just using it via remark-cli. Would like a `--format=vim` (or `--format=compact`) option that outputs as:
`filename.md:12:4 warning ATX headers present`
-- basically having everything on one line with single character (space or colon, doesn't matter) delimiters. This translates to `%f:%l:%c %tarning %m` in vim's `errorformat` (where `%t` captures the first character to get the warning/error type, using the literal `arning` is optional, a `%*` group could be used instead)

**Comment by wooorm** [comment]
Could you open an issue on [unified-engine](https://github.com/wooorm/unified-engine)? That’s the correct place for the code.

I’m suggesting that they work like plugins (but not in config files), and receive a list of `vfile`s (like the current formatter, and Sindre’s formatter), and either return a string.
